---
title: "MALoaiza_forcast"
author: '"Mario Loaiza'
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
library(tidyverse)
library(lubridate)
library(car)
library(RcmdrMisc)
library(lmtest)
library(MASS)
library(leaps)
```

```{r get-targets, message=F}
#read in the targets data
targets <- read_csv('https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz')

# read in the sites data
aquatic_sites <- read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-targets/main/NEON_Field_Site_Metadata_20220412.csv") |>
  dplyr::filter(aquatics == 1)

lake_sites <- aquatic_sites %>%
  filter(field_site_subtype == 'Lake')

# Filter the targets
targets <- targets %>%
  filter(site_id %in% lake_sites$field_site_id,
         variable == 'temperature')
```


Other variable names can be found at <https://projects.ecoforecast.org/neon4cast-docs/Shared-Forecast-Drivers.html#stage-3>

```{r}
met_variables <- c("air_temperature", "air_pressure","relative_humidity",
                   "surface_downwelling_longwave_flux_in_air",
                   "surface_downwelling_shortwave_flux_in_air", 
                   "precipitation_flux", "eastward_wind",
                   "northward_wind")
```


```{r get-NOAA-past, message = F}

# Past stacked weather
noaa_past_s3 <- neon4cast::noaa_stage3()

noaa_past <- noaa_past_s3  |> 
  dplyr::filter(site_id %in% lake_sites$field_site_id,
                datetime >= ymd('2017-01-01'),
                variable %in% met_variables) |> 
  dplyr::collect()

# aggregate the past to mean values
noaa_past_mean <- noaa_past |> 
  mutate(datetime = as_date(datetime)) |> 
  group_by(datetime, site_id, variable) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |>
  # convert air temperature to Celsius if it is included in the weather data
  mutate(prediction = ifelse(variable == "air_temperature", prediction - 273.15, prediction)) |>
  pivot_wider(names_from = variable, values_from = prediction) 
```

```{r get-NOAA-future, message = F}
# Future weather
# New forecast only available at 5am UTC the next day
forecast_date <- Sys.Date()
noaa_date <- forecast_date - days(1)

noaa_future_s3 <- neon4cast::noaa_stage2(start_date = as.character(noaa_date))

noaa_future <- noaa_future_s3 |> 
  dplyr::filter(datetime >= forecast_date,
                site_id %in% lake_sites$field_site_id,
                variable %in% met_variables) |> 
  collect()

noaa_future_daily <- noaa_future |> 
  mutate(datetime = as_date(datetime)) |> 
  # mean daily forecasts at each site per ensemble
  group_by(datetime, site_id, parameter, variable) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |> 
  # convert air temperature to Celsius if it is included in the weather data
  mutate(prediction = ifelse(variable == "air_temperature", prediction - 273.15,
                             prediction)) |> 
  pivot_wider(names_from = variable, values_from = prediction) ##|> select(any_of(c('datetime', 'site_id', met_variables, 'parameter')))
```

```{r model-setup}
# Generate a dataframe to fit the model to 
targets_lm <- targets |> 
  pivot_wider(names_from = 'variable', values_from = 'observation') |> 
  left_join(noaa_past_mean, 
            by = c("datetime","site_id"))

# Loop through each site to fit the model
forecast_df <- NULL
```

Correlation matrix
```{r}
pairs(targets_lm[,3:11], pch=16, cex=.7)
```

```{r}
# round off correlation values 
round(cor(targets_lm[,3:11], use = "pairwise.complete.obs"), 3)
```


```{r}
# Full main effects model
m1 <- lm(temperature ~ ., data=targets_lm[,c(-1,-2)])
summary(m1)
avPlots(m1)
```

```{r}
m2 <- lm(temperature ~ .*., data=targets_lm[,c(-1,-2)])
summary(m2)
```

```{r}
# Can check independence by plotting residuals by each predictor
# Just one example: 
res.m1 = rstandard(m1)
plot(targets_lm$air_temperature,res.m1, pch=16)
abline(h=0)

# Check for independence and constant variance
# Want even scatter around zero across whole plot
plot(m1$fitted,res.m1, pch=16, ylab="standardized residual", xlab = "fitted value")
abline(h=0, col="blue")

# Check for constant variance with Breusch-Pagan test
bptest(m1)

# Check for normality with qqplot
qqnorm(res.m1, col="blue")
qqline(res.m1)

# Check for normality with Shapiro-Wilk test
shapiro.test(res.m1)

# You can also use the plot function with the model object to get useful 
# residual plots, you need to hit return in the console to the plots
plot(m1)


# Check for multicollinearity
vif(m1)


```

```{r}
models <- list(
  model1 = lm(site_target$temperature ~ poly(site_target$air_temperature, degree = 2) +
                poly(site_target$surface_downwelling_shortwave_flux_in_air, degree = 2)),
  model2 = lm(site_target$temperature ~ poly(site_target$air_temperature, degree = 2) * 
                poly(site_target$surface_downwelling_shortwave_flux_in_air, degree = 2)),
  model3 = lm(site_target$temperature ~ poly(site_target$air_temperature, degree = 2) +
              poly(site_target$surface_downwelling_shortwave_flux_in_air, degree = 2)+
              lag(site_target$temperature, 1)),
  model4 = lm(site_target$temperature ~ poly(site_target$air_temperature, degree = 2) *
              poly(site_target$surface_downwelling_shortwave_flux_in_air, degree = 2)+
              lag(site_target$temperature, 1)),           
  model5 = lm(site_target$temperature ~ poly(site_target$air_temperature, degree = 2) +
                poly(site_target$surface_downwelling_shortwave_flux_in_air, degree = 2) +
                lag(site_target$temperature, 1) + 
                lag(site_target$temperature, 2)),
  model6 = lm(site_target$temperature ~ poly(site_target$air_temperature, degree = 2) +
                lag(site_target$temperature, 1)),
  model7 = lm(site_target$temperature ~ site_target$air_temperature + 
                lag(site_target$temperature, 1)),
  model8 = lm(site_target$temperature ~ poly(site_target$air_temperature, degree = 1) +
                site_target$surface_downwelling_shortwave_flux_in_air+
                lag(site_target$temperature, 1)))
```


```{r}

model2<- list(
  longwaveP = lm(temperature ~ air_temperature + 
                 poly(surface_downwelling_longwave_flux_in_air, degree = 1), data = targets_lm_noNA),
  
  longwavePp = lm(temperature ~ poly(air_temperature,  degree = 1)+ 
                 poly(surface_downwelling_longwave_flux_in_air, degree = 1), data = targets_lm_noNA),
  
  ewindP = lm(temperature ~ air_temperature + 
                 poly(eastward_wind, degree = 1), data = targets_lm_noNA),
  
  ewindPp = lm(temperature ~ poly(air_temperature,  degree = 1) + 
                 poly(eastward_wind, degree = 1), data = targets_lm_noNA),
  
  longwavePplag = lm(temperature ~ poly(air_temperature, degree = 1) +
                surface_downwelling_longwave_flux_in_air+
                lag(temperature, 1), data = targets_lm_noNA),
  ewindPlag = lm(temperature ~ poly(air_temperature, degree = 1) +
                eastward_wind+
                lag(temperature, 1), data = targets_lm_noNA),
  ewindPplag = lm(temperature ~ poly(air_temperature, degree = 1) +
                poly(eastward_wind, degree = 1)+
                lag(temperature, 1), data = targets_lm_noNA),
  longwave = lm(temperature ~ poly(surface_downwelling_longwave_flux_in_air, degree = 1) + 
                 poly(eastward_wind, degree = 1), data = targets_lm_noNA)
)
```







```{r}
# deleted NA
targets_lm_noNA <- na.omit(targets_lm)
# create starting model for forward selection
m.start1 <- lm(temperature ~ 1, data=targets_lm_noNA[,c(-1,-2)])

# run stepwise selection - starting with null model
tem_for <- stepAIC(m.start1, direction="forward",
                      scope=list(upper= ~ air_temperature + surface_downwelling_longwave_flux_in_air + air_pressure + relative_humidity + surface_downwelling_longwave_flux_in_air + surface_downwelling_shortwave_flux_in_air + precipitation_flux+ eastward_wind + northward_wind))

# print out best model according to forward selection
tem_for
```


```{r}

targets_lm_noNA <- na.omit(targets_lm)
# create starting model for backward selection
m.start <- lm(temperature ~ ., data=targets_lm_noNA[,c(-1,-2)])

# run backward selection
tem_back <- stepAIC(m.start, direction="backward", trace=1)

# print out best model according to backward selection
tem_back 
```

```{r}
# run stepwise selection - starting with full model
drivers_both <- stepAIC(m.start, direction="both", trace=1)
drivers_both # print out best model according to stepwise selection

# run stepwise selection - starting with null model
drivers_both2 <- stepAIC(m.start1, direction="both", trace=1,
                      scope=list(upper= ~ air_temperature + surface_downwelling_longwave_flux_in_air + air_pressure + relative_humidity + surface_downwelling_longwave_flux_in_air + surface_downwelling_shortwave_flux_in_air + precipitation_flux+ eastward_wind + northward_wind))

summary(drivers_both2) 
```


Forward/Backward/Stepwise with BIC
```{r}
#Backward Elimination
drivers.bic.back <- stepwise(m.start, direction="backward", 
                           trace=1, criterion="BIC") 
#Forward Selection
drivers.bic.fwd <- stepwise(m.start, direction="forward", 
                          trace=1, criterion="BIC")
#Stepwise Selection
drivers.bic.both <- stepwise(m.start, direction="backward/forward",
                           trace=1, criterion="BIC")
```


