on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"

jobs:
  run_forecast:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Run automatic prediction file
        run: Rscript -e 'rmarkdown::render(input = "Submit_forecast/forecast_code_template.Rmd")'